@startuml
!include ./Poligono.puml
!include ./SrPalito.puml
!include ./Mundo.puml
!include ./Spline.puml
!include ./Retangulo.puml
!include ./Objeto.puml
!include ./Ponto.puml
!include ./Circulo.puml
!include ./SegReta.puml
!include ./Program.puml
!include ./obj/Debug/net6.0/CG_N3.AssemblyInfo.puml
!include ./obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
@enduml
